storePassword=TeeCoin2018!@#
keyPassword=TeeCoin2018!@#
keyAlias=TeecoinRewardAndroidKey
storeFile=TeeCoinAndroidKeyStore
# get key hash release for Login Facebook : change path -> enter keyPassword
# keytool -exportcert -alias TeecoinRewardAndroidKey -keystore /Users/tu/Documents/PROJECT/TeeCoinApp/TeeCoinAndroidKeyStore.jks | openssl sha1 -binary | openssl base64
# keytool -exportcert -alias TeecoinRewardAndroidKey -keystore /Users/ngovihung/Documents/Projects/teecoin_reward_android/TeeCoinAndroidKeyStore.jks | openssl sha1 -binary | openssl base64