// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  typedef PublicKey AccountID;

//  ===========================================================================
public class AccountID  {
  private PublicKey AccountID;
  public PublicKey getAccountID() {
    return this.AccountID;
  }
  public void setAccountID(PublicKey value) {
    this.AccountID = value;
  }
  public static void encode(XdrDataOutputStream stream, org.stellar.sdk.xdr.AccountID encodedAccountID) throws IOException {
  PublicKey.encode(stream, encodedAccountID.AccountID);
  }
  public static org.stellar.sdk.xdr.AccountID decode(XdrDataInputStream stream) throws IOException {
    org.stellar.sdk.xdr.AccountID decodedAccountID = new AccountID();
  decodedAccountID.AccountID = PublicKey.decode(stream);
    return decodedAccountID;
  }
}
