// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  typedef PublicKey NodeID;

//  ===========================================================================
public class NodeID  {
  private PublicKey NodeID;
  public PublicKey getNodeID() {
    return this.NodeID;
  }
  public void setNodeID(PublicKey value) {
    this.NodeID = value;
  }
  public static void encode(XdrDataOutputStream stream, org.stellar.sdk.xdr.NodeID encodedNodeID) throws IOException {
  PublicKey.encode(stream, encodedNodeID.NodeID);
  }
  public static org.stellar.sdk.xdr.NodeID decode(XdrDataInputStream stream) throws IOException {
    org.stellar.sdk.xdr.NodeID decodedNodeID = new NodeID();
  decodedNodeID.NodeID = PublicKey.decode(stream);
    return decodedNodeID;
  }
}
