// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  typedef uint64 SequenceNumber;

//  ===========================================================================
public class SequenceNumber  {
  private Uint64 SequenceNumber;
  public Uint64 getSequenceNumber() {
    return this.SequenceNumber;
  }
  public void setSequenceNumber(Uint64 value) {
    this.SequenceNumber = value;
  }
  public static void encode(XdrDataOutputStream stream, org.stellar.sdk.xdr.SequenceNumber encodedSequenceNumber) throws IOException {
  Uint64.encode(stream, encodedSequenceNumber.SequenceNumber);
  }
  public static org.stellar.sdk.xdr.SequenceNumber decode(XdrDataInputStream stream) throws IOException {
    org.stellar.sdk.xdr.SequenceNumber decodedSequenceNumber = new SequenceNumber();
  decodedSequenceNumber.SequenceNumber = Uint64.decode(stream);
    return decodedSequenceNumber;
  }
}
