// Automatically generated by xdrgen 
// DO NOT EDIT or your changes may be overwritten

package org.stellar.sdk.xdr;


import java.io.IOException;

// === xdr source ============================================================

//  typedef opaque Value<>;

//  ===========================================================================
public class Value  {
  private byte[] Value;
  public byte[] getValue() {
    return this.Value;
  }
  public void setValue(byte[] value) {
    this.Value = value;
  }
  public static void encode(XdrDataOutputStream stream, org.stellar.sdk.xdr.Value encodedValue) throws IOException {
  int Valuesize = encodedValue.Value.length;
  stream.writeInt(Valuesize);
  stream.write(encodedValue.getValue(), 0, Valuesize);
  }
  public static org.stellar.sdk.xdr.Value decode(XdrDataInputStream stream) throws IOException {
    org.stellar.sdk.xdr.Value decodedValue = new Value();
  int Valuesize = stream.readInt();
  decodedValue.Value = new byte[Valuesize];
  stream.read(decodedValue.Value, 0, Valuesize);
    return decodedValue;
  }
}
